### ISSUE TITLE
Give credit for your end portal mixin

### ISSUE THREAD

**Issue by xanthian** [NyakoFox/NyakoMod#13]
the fact you left bedrockDropsItself in there.. 😂

https://github.com/xanthian/bedrockbreakers/blob/master/src/main/java/net/xanthian/bedrockbreakers/mixin/BlocksMixin.java

**Comment by NyakoFox** [comment]
oh i guess i forgot to add the author comment, i think i just quickly copied it from LlamaLad7. i'll add a comment crediting him
